#!/bin/sh

if [ "${ADT:-}" = "skip" ]; then
	echo "Skipping autopkgtests (ADT is set)"
	exit 0
fi

set -ex

cd /tmp/buildd/*/debian/..

if [ ! -f debian/tests/control ]; then
	echo "Package does not have autopkgtest support, debian/tests/control is missing"
	exit 0
fi

if [ ! -f debian/files ]; then
	echo "Package source is not built, debian/files is missing"
	exit 1
fi

# environment variable for postgresql-common testsuite
export PG_UMASKS="077"

apt-get install -y autopkgtest apt-utils pbuilder newpid

# launch adt-run in a new PID namespace so several testsuites can run in parallel
newpid adt-run \
	--summary $PWD/autopkgtest.summary \
	/tmp/buildd/*.deb \
	--built-tree $PWD \
	--- adt-virt-null || EXIT=$?

case ${EXIT:-0} in
	2|4|6|8) # some test failed, exit 0 here and let adtsummary2junit report the failure
		exit 0
		;;
	*)
		exit ${EXIT:-0}
		;;
esac
