#!/bin/sh

set -eu

PBUILDER_BUILD="/home/pbuilder.buexcl/build"

touch /testfile.$$
BUILD=$PBUILDER_BUILD/*/testfile.$$
rm -f /testfile.$$

if ! test -f $BUILD; then
	echo "Could not determine our build directory in $PBUILDER_BUILD"
	printenv | sort
	exit 1
fi

COPY="$PBUILDER_BUILD/${BUILD_TAG/\//_}"

echo "Preserving build chroot for inspection in $COPY"
cp -alx $BUILD $COPY

du -sh $COPY
