#!/bin/sh

QUEUE="${1:-incoming}"
[ "$QUEUE" = "incoming" ] || exit 0
REPREPRO_BASE_DIR="/srv/apt/repo"

/usr/bin/reprepro -b "$REPREPRO_BASE_DIR" --morguedir "$REPREPRO_BASE_DIR/morgue" --verbose processincoming pgdg
