#!/bin/sh

# trigger builds for a distribution
# package is comma or space-separated list

# ./build-source-and-one-dist -c debsso.p12:asdf -d stretch prefix

set -eu

cert="${0%/*}/debsso.p12:asdf"

while getopts "b:d:c:r:" opt ; do
	case $opt in
	b) branch="$OPTARG" ;;
	d) distribution="$OPTARG" ;;
	c) cert="$OPTARG" ;;
	r) revision="$OPTARG" ;;
	*) exit 5 ;;
	esac
done
# shift away args
shift $(($OPTIND - 1))

IFS=", "

set -x

for pkg in "$@"; do
    curl --cert "$cert" --cert-type p12 \
      "https://pgdgbuild.dus.dg-i.net/job/build-source-and-one-dist/buildWithParameters" \
      --data "token=buildnow&PACKAGE=$pkg&revision=${revision:-1}&branch=${branch:-}&buildtype=normal&distribution=$distribution"
done
