#!/bin/sh

set -eu

LISTSDIR="/home/chroot/$distribution-$architecture/var/lib/apt/lists"
DISTSDIR="/home/jenkins/dists"

# main package list
PKG="$LISTSDIR/*_dists_${distribution}_main_binary-${architecture}_Packages"

# include universe on ubuntu
for FILE in $LISTSDIR/*_dists_${distribution}_universe_binary-${architecture}_Packages ; do
	[ -f "$FILE" ] || continue
	# work around dose-debcheck dying on a Python_ field
	TMPPKG=$(mktemp ${distribution}_universe_binary-${architecture}_Packages.XXXXXX)
	trap "rm -f $TMPPKG" 0 2 3 15
	sed -e 's/^Python_/Python-/' $FILE > $TMPPKG
	PKG="$PKG $TMPPKG"
done

# include backports on debian
for FILE in $LISTSDIR/*_dists_${distribution}-backports_main_binary-${architecture}_Packages ; do
	[ -f "$FILE" ] || continue
	PKG="$PKG $FILE"
done

# include pgdg dists
case $stage in
	production)
		DIST="$distribution-pgdg"
		PKG="$PKG $DISTSDIR/$DIST/main/binary-${architecture}/Packages"
		PKG="$PKG $DISTSDIR/$DIST-testing/main/binary-${architecture}/Packages"
		;;
	testing)
		DIST="$distribution-pgdg-testing"
		PKG="$PKG $DISTSDIR/$DIST/main/binary-${architecture}/Packages"
		;;
	*) echo "Bad stage $stage" ; exit 1 ;;
esac

set -x

# run builddebcheck
dose-builddebcheck -v -f -e --deb-native-arch=$architecture \
	$PKG $DISTSDIR/$DIST/main/source/Sources.gz
