#!/bin/sh

set -eu

LISTSDIR="/home/chroot/$distribution-$architecture/var/lib/apt/lists"

case $stage in
	production) DIST="$distribution-pgdg" ;;
	testing)    DIST="$distribution-pgdg-testing" ;;
	*) echo "Bad stage $stage" ; exit 1 ;;
esac

# include universe on ubuntu
for FILE in $LISTSDIR/*_dists_${distribution}_universe_binary-${architecture}_Packages ; do
	[ -f "$FILE" ] || continue
	EXTRABG="--bg $FILE"
done

# include N.N components on sid
case $distribution in
	sid) EXTRAFG="--fg $DIST/*.*/binary-${architecture}/Packages" ;;
esac

set -x

# fetch packages lists
rsync -Pav --delete atalia.postgresql.org:/srv/apt/pub/repos/apt/dists/$DIST .

# run debcheck
dose-debcheck -v -f -e \
	--bg $LISTSDIR/*_dists_${distribution}_main_binary-${architecture}_Packages \
	${EXTRABG:-} \
	--fg $DIST/main/binary-${architecture}/Packages \
	${EXTRAFG:-}
