#!/bin/sh

HOST="atalia.postgresql.org"
QUEUE="${1:-incoming}"

trap "rm -rf *" 0 2 3 15

ls -AlR

[ "$QUEUE" = "discard" ] && exit 0

set -eux

CHANGES="$(find . -name '*.changes')"

dcmd chmod a+r $CHANGES

# work around reprepro #808558
perl -i -pe 's/ (\S+)/ $1 $1-dbgsym/g if /^Binary:/' $CHANGES

# upload only version-specific .deb files when requested
if [ "${upload:-all}" = "extension-only" ]; then
	for c in $CHANGES; do
		case $CHANGES in
			*_source.changes) continue ;;
		esac
		NONEXTDEBS=$(dcmd --deb echo $c | xargs -n1 | egrep -v -- '[^_]-[1-9][0-9]?\.[0-9][-_]' | sed -e 's!.*/!!')
		changestool $c dumbremove $NONEXTDEBS
	done
fi

dcmd rsync -av $CHANGES $HOST:/srv/apt/$QUEUE

# call processincoming once for all packages uploaded
ssh $HOST sudo -u aptuser /srv/apt/apt.postgresql.org/repo/processincoming $QUEUE

# trap will clean up here
