#!/bin/sh

# The MIT License
#
# Copyright (c) 2011,2012 by Michael Prokop <mika@debian.org>
# Copyright (c) 2012-2017 by Christoph Berg <myon@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e
set -u

if [ -z "${PACKAGE:-}" ]; then
  PACKAGE="${JOB_NAME%-source*}"
fi

echo "PACKAGE=$PACKAGE"
echo "BUILD_NUMBER=${BUILD_NUMBER:-}"
echo "JOB_NAME=${JOB_NAME:-}"
echo "GIT_COMMIT=${GIT_COMMIT:-}"
echo "BZR_REVISION=${BZR_REVISION:-}"
echo "SVN_REVISION=${SVN_REVISION:-}"
echo "buildtype=${buildtype:-}"
echo "distribution=${distribution:=sid}"
echo "branch=${branch:-}"
echo "merge=${merge:-}"
echo "revision=${revision:-}"

set -x

# which PostgreSQL major version to pull libpq et al. from (should be last stable release)
PGLIBVER="9.6"
# which libpq version to use in sid (latest beta)
PGLIBVER_SID="9.6"

[ -n "${DEBEMAIL:-}" ] || export DEBEMAIL="apt.postgresql.org autobuilder <pgsql-pkg-debian@postgresql.org>"

export PG_SUPPORTED_VERSIONS="pgdg"

REVERTS="debian/changelog debian/control debian/rules"

if [ "${GIT_COMMIT:-}" ]; then
  VCS=git
  VCS_REVISION="$GIT_COMMIT/git"
  VCS_REVERT="git checkout"
  # building in 'source'
  cd source
  RESULT=../result
elif [ "${BZR_REVISION:-}" ] ; then
  VCS=bzr
  VCS_REVISION="$BZR_REVISION/bzr"
  VCS_REVERT="bzr revert"
  # building in '.'
  RESULT=result
elif [ "${SVN_REVISION:-}" ] ; then
  VCS=svn
  VCS_REVISION="$SVN_REVISION/svn"
  VCS_REVERT="svn revert"
  # building in 'source'
  cd source
  RESULT=../result
elif [ "${apt_suite:-}" ] ; then
  rm -rf $PACKAGE* source
  apt-get source -d $PACKAGE/$apt_suite
  dpkg-source -x $PACKAGE*.dsc source
  VCS=debian
  VCS_REVISION="Debian $apt_suite source rebuild"
  VCS_REVERT=":"
  cd source
  RESULT=../result
else # use source package in current directory
  rm -rf source
  dpkg-source -x $PACKAGE*.dsc source
  VCS="dsc"
  VCS_REVISION="source rebuild"
  VCS_REVERT=":"
  cd source
  RESULT=../result
fi

# remove artifacts from last build
rm -rf $RESULT ../*.dsc ../*.debian.tar.* ../*.diff.gz ../*.changes

# merge with another branch
if [ "${merge:-}" ]; then
  git remote add debian https://anonscm.debian.org/git/pkg-postgresql/postgresql.git || :
  git fetch debian
  git reset --hard $branch
  git clean -xdf
  git merge -m "Merge with https://anonscm.debian.org/git/pkg-postgresql/postgresql.git ($merge)" debian/$merge
fi

# clean up behind a possibly broken last job
cleanup () {
  [ "${NO_ORIGTARGZ:-}" ] && QUILT_PATCHES=debian/patches quilt pop -a
  $VCS_REVERT $REVERTS || :
}
trap "cleanup" 0 2 3 15
cleanup

# get newest version number from changelog
PREVIOUS_VERSION=$(dpkg-parsechangelog --count 1 | awk '/^Version: / {print $2}')
BASE_VERSION=$(echo $PREVIOUS_VERSION | sed -e 's/[~.]\(pgdg\|pgapt\).*//')

case ${distribution:-} in
  # Debian
  sid)     PGLIBVER="$PGLIBVER_SID" # use latest beta on sid
           PGDG_DISTRIBUTION="pgdg"      DISTRO="debian" RELEASE="unstable" ;;
  buster)  PGDG_DISTRIBUTION="pgdg100"   DISTRO="debian" RELEASE="10" ;;
  stretch) PGDG_DISTRIBUTION="pgdg90"    DISTRO="debian" RELEASE="9" ;;
  jessie)  PGDG_DISTRIBUTION="pgdg80"    DISTRO="debian" RELEASE="8" ;;
  wheezy)  PGDG_DISTRIBUTION="pgdg70"    DISTRO="debian" RELEASE="7" ;;
  squeeze) PGDG_DISTRIBUTION="pgdg60"    DISTRO="debian" RELEASE="6.0" ;;
  lenny)   PGDG_DISTRIBUTION="pgdg50"    DISTRO="debian" RELEASE="5.0" ;;
  etch)    PGDG_DISTRIBUTION="pgdg40"    DISTRO="debian" RELEASE="4.1" ;;
  # Ubuntu
  zesty)   PGDG_DISTRIBUTION="pgdg17.04" DISTRO="ubuntu" RELEASE="17.04" ;;
  xenial)  PGDG_DISTRIBUTION="pgdg16.04" DISTRO="ubuntu" RELEASE="16.04" ;;
  wily)    PGDG_DISTRIBUTION="pgdg15.10" DISTRO="ubuntu" RELEASE="15.10" ;;
  utopic)  PGDG_DISTRIBUTION="pgdg14.10" DISTRO="ubuntu" RELEASE="14.10" ;;
  trusty)  PGDG_DISTRIBUTION="pgdg14.04" DISTRO="ubuntu" RELEASE="14.04" ;;
  saucy)   PGDG_DISTRIBUTION="pgdg13.10" DISTRO="ubuntu" RELEASE="13.10" ;;
  precise) PGDG_DISTRIBUTION="pgdg12.4"  DISTRO="ubuntu" RELEASE="12.04" ;;
  lucid)   PGDG_DISTRIBUTION="pgdg10.4"  DISTRO="ubuntu" RELEASE="10.04" ;;
  *) echo "Unknown distribution ${distribution:-}" >&2 ; exit 1 ;;
esac

# tell /usr/share/postgresql-common/supported-versions which distro/release we are targetting
export DISTRO RELEASE

# for postgresql server packages, move packages to a separate components
# = $PGLIBVER: main
# < $PGLIBVER: lib packages to N.N, rest to main
# > $PGLIBVER: all packages to N.N
set_package_component ()
{
  PKGPREFIX="$1" # empty ok
  SECTION="$2"
  echo "Setting $PKGPREFIX* packages component to '$SECTION'"
  perl -i -000 -pe "s/^Section: (?:.+\/)?(.*)/Section: $SECTION\$1/m if (/^$PKGPREFIX/m)" \
    debian/control
}
show_package_sections ()
{
  perl -000 -ne 'if (/^(Package: .*)/m) { print "$1 "; print "$1\n" if /^(Section: .*)/m; }' \
    debian/control
}
case $PACKAGE in
  postgresql-?.?|postgresql-??)
    PGVERSION=${PACKAGE#postgresql-}
    if dpkg --compare-versions $PGVERSION lt $PGLIBVER; then
      set_package_component "Package: lib" "$PGVERSION\/"
    elif dpkg --compare-versions $PGVERSION gt $PGLIBVER; then
      set_package_component "" "$PGVERSION\/"
    else
      set_package_component "" ""
    fi
    show_package_sections

    # enable cassert on sid
    if [ "$distribution" = "sid" ]; then
      sed -i -e 's/^#CASSERT_FLAGS/CASSERT_FLAGS/' debian/rules
    fi
    ;;
esac

# tweaks to get packages in older dists working
case $PACKAGE in
  postgresql-9.[56]|postgresql-??)
    case ${distribution:-} in
      wheezy|squeeze|precise)
        sed -i -e '/sepgsql\|selinux/d' debian/control debian/rules debian/postgresql-*.install
        ;;
    esac
    case ${distribution:-} in
      wheezy|squeeze|precise|trusty)
        sed -i -e '/systemd/d' debian/control debian/rules # applies to postgresql-9.6+ only
        ;;
    esac
    ;;

  postgresql-common)
    case ${distribution:-} in
      trusty|wheezy)
        TWEAK="Remove systemd dependency"
        sed -i -e '/dh-systemd/d' debian/control
        sed -i -e '/^WITH_SYSTEMD/d' debian/rules
        ;;
    esac
    ;;

  autopkgtest|dh-exec|libdbd-pg-perl)
    DOT='~' ;;

  pgloader|bordeaux-threads|buildapp|cffi|cl-*|sbcl) # pgloader and build-deps
    DOT='~' ;;

  gdal)
    DOT='~'
    case ${distribution:-} in
      precise) # precise's freexl is too old
        sed -i -e "s/, libfreexl-dev[^,]*,/,/" debian/control
        sed -i -e "s/--with-freexl=yes/--with-freexl=no/" debian/rules
      ;;
    esac
    ;;

  geos|docbook-xsl)
    DOT='~'
    ;;

  pgbouncer)
    case ${distribution:-} in
      wheezy|trusty|xenial)
        TWEAK="Revert switch to c-ares because it is too old on $distribution"
        sed -i -e '/libc-ares-dev/d' debian/control
        sed -i -e 's/--with-cares=yes/--with-cares=no/' debian/rules
        sed -i -e '/1.7.2-3/,/28 Jun 2017/d' debian/NEWS # remove news item about c-ares switch
        ;;
    esac
    ;;

  pgpool2)
    case ${distribution:-} in
      squeeze|wheezy|lucid|precise|saucy|trusty) # remove systemd dependency
        sed -i -e '/dh-systemd/d' debian/control debian/control.in
        ;;
    esac
    case ${distribution:-} in
      squeeze|wheezy|lucid|precise) # manually run libtoolize
        echo "override_dh_autoreconf:" >> debian/rules
        echo "	libtoolize" >> debian/rules
        echo "	dh_autoreconf" >> debian/rules
        ;;
    esac
    ;;

  postgis)
    for version in $(/usr/share/postgresql-common/supported-versions); do
      sed -i -e "s/^Build-Depends: /Build-Depends: postgresql-$version, /" debian/control
    done
    case ${distribution:-} in
      wheezy) # we do not want libjson-c-dev from bpo, just wheezy's libjson0-dev
        sed -i -e 's/libjson-c-dev | //' debian/control debian/control.in
        ;;
    esac
    case ${distribution:-} in
      # There's no have libsfcgal-dev before stretch or wily. However,
      # there's a backport to jessie. Pgapt provides libsfcgal for
      # jessie as well, so it remains independent of jessie-backports.
      wheezy|squeeze|wily|trusty|precise)
        sed -i -e '/libsfcgal-dev/d' debian/control debian/control.in
        sed -i -e "/sfcgal/Id" debian/liblwgeom-*.symbols
        ;;
    esac
    ;;

  psqlodbc)
    case ${distribution:-} in
      wheezy|precise|saucy|trusty) # odbc-postgresql conflicts with libiodbc2, skip iodbc test here
        sed -i -e 's/, iodbc//' debian/tests/control*
        ;;
    esac
    ;;

  skytools3)
    case ${distribution:-} in
      squeeze|wheezy|lucid|precise)
        # remove dh_python2 dependency
        sed -i -e 's/ dh-python,//' debian/control debian/control.in
        # switch to standard sequencer
        sed -i -e 's/ --with python2//' debian/rules
        ;;
    esac
    ;;

  barman|barman-cli)
    case ${distribution:-} in
      wheezy|precise)
        # remove dh_python2 dependency, the python2 sequencer is
        # provided by python package
        sed -i -e 's/, dh-python//' debian/control
        ;;
    esac
    ;;

esac


# for binnmu-style rebuilds, add a "revision" parameter to the source job
if [ "${revision:-}" ] ; then
  PGDG_REVISION="+${revision}"
else
  case $PREVIOUS_VERSION in
    *pgdg*|*pgapt*) PGDG_REVISION=$(echo $PREVIOUS_VERSION | sed -e 's/.*+/+/') ;;
    *) PGDG_REVISION="+1" ;;
  esac
fi

# set $UNRELEASED to force using a ~version
CL_DISTRIBUTION=$(dpkg-parsechangelog --count 1 | awk '/^Distribution/ {print $2}')
if [ "${UNRELEASED:-}" ] || echo "$CL_DISTRIBUTION" | grep -q "UNRELEASED" ; then
  case ${buildtype:-} in
  snapshot*) # create a ~ orig tarball
    TILDE='~'
    [ $buildtype = 'snapshot-dot' ] && TILDE='.'
    DATE="$(date -u +%Y%m%d.%H%M)"
    BASE_VERSION=$(echo "$BASE_VERSION" | sed -e "s/-/$TILDE$DATE-/")
    echo "1.0" > debian/source/format
    REVERTS="$REVERTS debian/source/format"
    NO_ORIGTARGZ="1.0"
    QUILT_PATCHES=debian/patches quilt push -a
    ;;
  esac
  SHORT_REVISION=$(echo $VCS_REVISION | cut -c 1-7)
  SUFFIX="~${BUILD_NUMBER}.${VCS}${SHORT_REVISION}"
else
  SUFFIX=""
fi

# $DOT defaults to '.', but can be set to '~'
VERSION_STRING="$BASE_VERSION$SUFFIX${DOT:-.}$PGDG_DISTRIBUTION$PGDG_REVISION"
dch --force-distribution --distribution="$distribution-pgdg" \
  --release-heuristic log -b --newversion=$VERSION_STRING -- \
  "Rebuild for $distribution-pgdg (${BUILD_TAG:-}, $VCS_REVISION)" ${TWEAK:-}

[ "${NO_ORIGTARGZ:-}" ] || origtargz --tar-only --path=$HOME/tarballs --unpack

if ! [ -f debian/control ] ; then
  make -f debian/rules debian/control
fi

dpkg-buildpackage -uc -us -nc -d -sa -S -i -I

mkdir $RESULT
dcmd cp -alv ../${PACKAGE}_*.changes $RESULT

# vim:foldmethod=marker ts=2 ft=sh ai expandtab sw=2
