#!/bin/sh

# run autopkgtest in schroot

set -eu

PACKAGE="$1"
CHROOT="chroot:${distribution:=sid}-pgdg-${architecture:=amd64}-sbuild"

set -x

newpid-netns schroot -c $CHROOT -u root sh <<-EOF
	set -eu
	export PG_SUPPORTED_VERSIONS="${PG_SUPPORTED_VERSIONS:=pgdg}" # import from outer environment
	
	# make PG devel available if requested
	if [ "\$PG_SUPPORTED_VERSIONS" != "pgdg" ]; then
	  sed -i -e "s/main/main \$PG_SUPPORTED_VERSIONS/" /etc/apt/sources.list.d/pgdg.list
	fi
	
	( set -x; apt-get -y update)
	
	# convert list of supported versions to grep filter
	for ver in \$(/usr/share/postgresql-common/supported-versions); do
	  FILTER="\${FILTER:-} -e \$ver"
	done
	# find all binaries built from this source matching supported versions
	# (we need this because the source package will likely only list one)
	BINARIES=\$(cat /var/lib/apt/lists/*_Packages |
	  grep-dctrl --exact-match -S "$PACKAGE" --no-field-names -s Package |
	  fgrep \$FILTER | sort -u)
	
	# skip PG devel tests if packages have not been built yet
	if [ "\$PG_SUPPORTED_VERSIONS" != "pgdg" ] && [ -z "\$BINARIES" ]; then
	  echo "No version \$PG_SUPPORTED_VERSIONS packages for $PACKAGE found, exiting"
	  exit 0
	fi
	
	if [ "\$PG_SUPPORTED_VERSIONS" != "pgdg" ]; then
	  BINARIES="\${BINARIES:-} postgresql-\$PG_SUPPORTED_VERSIONS postgresql-server-dev-\$PG_SUPPORTED_VERSIONS"
	fi
	
	if [ "\$BINARIES" ]; then
	  ( set -x; apt-get install -y \$BINARIES )
	fi
	
	# run autopkgtest
	if [ -x /usr/bin/autopkgtest ]; then
	  ( set -x; autopkgtest "$PACKAGE" -- null || EXIT=\$? )
	else
	  ( set -x; adt-run --apt-source "$PACKAGE" --- null || EXIT=\$? )
	fi
	case \${EXIT:-0} in
	  2|8) exit 0 ;; # tests skipped / no tests in this package
	  *) exit \${EXIT:-0} ;;
	esac
EOF

