#!/bin/sh

# The MIT License
#
# Copyright (c) 2012-2019 by Christoph Berg <myon@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# read pgapt config
for dir in . .. /home/jenkins/jenkins/workspace/apt.postgresql.org /home/buildd/workspace/apt.postgresql.org; do
  test -f $dir/pgapt.conf || continue
  . $dir/pgapt.conf
  break
done

# lock against concurrent apt-get update/upgrade operations on the source chroot
LOCKDIR="/var/lock/sbuild-package"
if ! test -d $LOCKDIR; then
  mkdir $LOCKDIR
  chgrp sbuild $LOCKDIR
  chmod 3775 $LOCKDIR
fi
umask 002

set -eux

flock --shared $LOCKDIR/${distribution:=sid}-${architecture:=amd64}.lock \
${wrap-newpid-netns} \
schroot -u root -c "chroot:$distribution-$architecture" -- sh <<EOF
set -eux

# /var/lib/jenkins will probably not exist
test -w \${HOME:-/does/not/exist} || export HOME=/tmp

# update pgdg.list for devel versions
case "$@" in
  *${PG_BETA_VERSION:-unset}*)
    sed -i -e "s/main/main ${PG_BETA_VERSION:-}/" /etc/apt/sources.list.d/pgdg.list ;;
  *${PG_DEVEL_VERSION:-unset}*)
    sed -i -e "s/main/main ${PG_DEVEL_VERSION:-}/" /etc/apt/sources.list.d/pgdg.list ;;
esac

# pick up new packages, most notably postgresql-common might have been updated
apt-get -y update || { sleep 60; apt-get -y update; }

export LC_ALL='en_US.UTF-8'
cd /usr/share/postgresql-common/
./testsuite -V -u 077 -i -v "$@"
EOF

# vim:sw=2
