#!/bin/sh

# The MIT License
#
# Copyright (c) 2012-2015 by Christoph Berg <myon@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# lock against concurrent apt-get update/upgrade operations on the source chroot
LOCKDIR="/var/lock/sbuild-package"
if ! test -d $LOCKDIR; then
  mkdir $LOCKDIR
  chgrp sbuild $LOCKDIR
  chmod 3775 $LOCKDIR
fi
umask 002

set -eux

flock --shared $LOCKDIR/$distribution-$architecture.lock \
schroot -u root -c "chroot:$distribution-$architecture" -- sh <<'EOF'
set -eux

# /var/lib/jenkins will probably not exist
test -w ${HOME:-/does/not/exist} || export HOME=/tmp

# libkrb5-dev needed for postgresql-9.0 and postgresql-9.1
apt-get install -y locales logrotate netcat-openbsd net-tools hunspell-en-us newpid libkrb5-dev
if ! dpkg -i *.deb; then
  apt-get install -fy
  dpkg -i *.deb
fi

dpkg -l 'libpq*' 'postgresql*' | cat

export LC_ALL='en_US.UTF-8'
cd /usr/share/postgresql-common/
newnet ./testsuite -V -u 077
EOF

# vim:sw=2
