#!/bin/sh

case $DEB_PG_SUPPORTED_VERSIONS in
  ""|pgdg) exit 0 ;;
esac

[ "$(id -u)" = "0" ] || SUDO="sudo"

set -x
$SUDO sed -i -e "s/main/main $DEB_PG_SUPPORTED_VERSIONS/" /etc/apt/sources.list.d/pgdg.list
