#!/bin/sh

# ./trigger-job -c debsso.p12:asdf apgdiff branch=debian

# ~/.netrc:
#machine pgdgbuild.dus.dg-i.net login <username> password <your-api-token>

set -eu

JOB="$1"
shift

set -x

curl --netrc \
  "https://pgdgbuild.dus.dg-i.net/job/$JOB/buildWithParameters" \
  --data "token=buildnow&$@"

#curl --netrc -X POST \
#  "https://pgdgbuild.dus.dg-i.net/job/$JOB/doDelete"
