#!/bin/sh

# ./trigger-job apgdiff branch=debian
# ./trigger-job postgresql-12-binaries 'binnmu_reason=Rebuild against python 3.8.&binnmu_version=1&matrix=distribution%3d%3d"bullseye"'
# ./trigger-job dput 'binaries=postgresql-12-binaries'

# ~/.netrc:
#machine pgdgbuild.dus.dg-i.net login <username> password <your-api-token>

set -eu

JOB="$1"
shift

set -x

curl --netrc \
  "https://pgdgbuild.dus.dg-i.net/job/$JOB/buildWithParameters" \
  --data "token=buildnow&$@"

#curl --netrc -X POST \
#  "https://pgdgbuild.dus.dg-i.net/job/$JOB/doDelete"
