#!/bin/sh

# trigger builds for a distribution
# package and distribution are comma or space-separated lists

# ./trigger-build-source -c debsso.crt:asdf -d stretch,zesty prefix

set -eu

while getopts "d:c:" opt ; do
	case $opt in
	d) distribution="$OPTARG" ;;
	c) cert="$OPTARG" ;;
	*) exit 5 ;;
	esac
done
# shift away args
shift $(($OPTIND - 1))

IFS=", "

set -x

for pkg in "$@"; do
  for dist in $distribution; do
    curl --cert "$cert" \
      "https://pgdgbuild.dus.dg-i.net/job/build-source/buildWithParameters" \
      --data "token=buildnow&PACKAGE=$pkg&distribution=$dist"
  done
done
