#!/bin/sh

set -eux

case ${distribution} in
	squeeze)
		PGVERSION="8.4"
		OLDDIST="squeeze"
		OLDPERL="5.10"
		NEWDIST="wheezy"
		NEWPERL="5.14"
		;;
	wheezy)
		OLDDIST="wheezy"
		OLDPERL="5.14"
		NEWDIST="sid"
		NEWPERL="5.18"
		PGVERSION="9.1"
		;;
esac

: "*** Removing pgdg sources.list"
rm -f /etc/apt/sources.list.d/pgdg.list
apt-get update

trap "service postgresql stop" 0 2 3 15

apt-get install -y postgresql-plperl-$PGVERSION
test -f /etc/postgresql/$PGVERSION/main/postgresql.conf || \
	pg_createcluster --start-conf=auto $PGVERSION main
service postgresql start
su -c "createuser --superuser $USER" postgres
export PGDATABASE="postgres"

psql <<'EOF'
CREATE EXTENSION plperl;
CREATE OR REPLACE FUNCTION perl_version() RETURNS text AS
$$ return sprintf "%vd", $^V; $$ LANGUAGE plperl;
CREATE EXTENSION plperlu;
CREATE OR REPLACE FUNCTION perl_versionu() RETURNS text AS
$$ return sprintf "%vd", $^V; $$ LANGUAGE plperlu;
EOF

: "*** Perl version on $OLDDIST is $OLDPERL"
psql -c 'SELECT perl_version()' | fgrep $OLDPERL
psql -c 'SELECT perl_versionu()' | fgrep $OLDPERL

: "*** Upgrading from $OLDDIST to $NEWDIST"
sed -i -e "s/$OLDDIST/$NEWDIST/g" -e '/security.*sid/d' /etc/apt/sources.list
apt-get update
apt-get install postgresql-plperl-$PGVERSION

: "*** Restarting PostgreSQL (this should actually not be necessary)"
service postgresql restart

: "*** Perl version on $NEWDIST is $NEWPERL"
psql -c 'SELECT perl_version()' | fgrep $NEWPERL
psql -c 'SELECT perl_versionu()' | fgrep $NEWPERL
